services:
  frontend:
    image: alzaine/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8081:80"
    environment:
      - VITE_GRAPHQL_URI=http://207.90.237.51:8082/graphql
      - VITE_SERVER_URI=http://207.90.237.51:8082
    restart: unless-stopped